### ISSUE TITLE
No module named 'networks.MSBDN-DFF-v1-1'

### ISSUE THREAD

**Issue by ChengBo5** [BookerDeWitt/MSBDN-DFF#10]
When I run test.py using the model.pkl file provided by the author, I ran into a problem:
`ModuleNotFoundError: No module named 'networks.MSBDN-DFF-v1-1'`
Does anyone encounter this problem and how to solve it？

**Comment by BookerDeWitt** [comment]
You can refer this post: #9

**Comment by ChengBo5** [comment]
That worked, thank you!
