### ISSUE TITLE
FileNotFoundError:No such file or directory: 'Logs/Output_MSBDN-DFF.txt'

### ISSUE THREAD

**Issue by sunfuxin111** [BookerDeWitt/MSBDN-DFF#11]
File "train.py",line 183,in<module>
  with open("Logs/Output_{}.txt".format(opt.name), "a+")as text_file:
FileNotFoundError:No such file or directory: 'Logs/Output_MSBDN-DFF.txt'

Hello, how can I solve this problem?

**Comment by BookerDeWitt** [comment]
Try to create a folder named 'Logs' first?

**Comment by sunfuxin111** [comment]
Thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Hang"<notifications@github.com&gt;; 
发送时间: 2021年2月19日(星期五) 下午3:26
收件人: "BookerDeWitt/MSBDN-DFF"<MSBDN-DFF@noreply.github.com&gt;; 
抄送: "情未了"<1143156657@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [BookerDeWitt/MSBDN-DFF] FileNotFoundError:No such file or directory: &#39;Logs/Output_MSBDN-DFF.txt&#39; (#11)






尝试先创建一个名为“日志”的文件夹？

—
您正在接收此消息，因为您创建了该线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
