### ISSUE TITLE
How do I need to modify the code to change the data set from.H5 to.Jpg format？

### ISSUE THREAD

**Issue by sym1998** [BookerDeWitt/MSBDN-DFF#13]
Please！

**Comment by BookerDeWitt** [comment]
You can read the data from .h5 file with "h5py" package.
Then you can switch the numpy format data to the image.

**Comment by sym1998** [comment]
Hello, I mean how to modify your code so that the training part does not use the. H5 data set, but uses the. JPG data set.

**Comment by dingyan1478** [comment]
Hello!
Do you know how to do it? I didn't use h5 file for training, just used. JPG file for training, but the training result is very bad, the output image has a mosaic effect, do you know why? Or does this network need to use H5 file for training?

**Comment by f-w-m** [comment]
> Hello!
> Do you know how to do it? I didn't use h5 file for training, just used. JPG file for training, but the training result is very bad, the output image has a mosaic effect, do you know why? Or does this network need to use H5 file for training?

Hello, I am very excited to see your work. Could you tell me how to use JPG files for training? @dingyan1478

**Comment by dingyan1478** [comment]
> > Hello! Do you know how to do it? I didn't use h5 file for training, just used. JPG file for training, but the training result is very bad, the output image has a mosaic effect, do you know why? Or does this network need to use H5 file for training?
> 
> Hello, I am very excited to see your work. Could you tell me how to use JPG files for training? @dingyan1478

I just changed the data preprocessing part and wrote the preprocessing code for JPG files. The other parts use the code provided by the author. However, in the process of training, the mosaic effect appeared for the first time, and then the super parameters in the code were modified according to the paper, and the effect was good.
I hope it can help you.

**Comment by f-w-m** [comment]
> > > Hello! Do you know how to do it? I didn't use h5 file for training, just used. JPG file for training, but the training result is very bad, the output image has a mosaic effect, do you know why? Or does this network need to use H5 file for training?
> > 
> > 
> > Hello, I am very excited to see your work. Could you tell me how to use JPG files for training? @dingyan1478
> 
> I just changed the data preprocessing part and wrote the preprocessing code for JPG files. The other parts use the code provided by the author. However, in the process of training, the mosaic effect appeared for the first time, and then the super parameters in the code were modified according to the paper, and the effect was good.
> I hope it can help you.

Thank you very much for your reply. I tried to write a code to solve it, but I couldn't solve it. I would be very grateful if you could send me a copy of your code for me to learn. Attach my email: fangwangming@126.com.

**Comment by Grass-clj** [comment]
> > > 你好！你知道怎么做吗？我没有使用 h5 文件进行训练，只是使用了。JPG文件进行训练，但训练结果很差，输出图像有马赛克效果，你知道为什么吗？还是这个网络需要使用H5文件进行训练？
> > 
> > 
> > 您好，我很高兴看到您的工作。你能告诉我如何使用JPG文件进行培训吗？@dingyan1478
> 
> 我只是更改了数据预处理部分，并为JPG文件编写了预处理代码。其他部分使用作者提供的代码。但是在训练的过程中，第一次出现了马赛克效果，然后根据论文修改了代码中的超级参数，效果不错。我希望它能帮助你。

您好，您的修改的预处理代码可以提供一下吗？如果不行那就祝您生活愉快。
