### ISSUE TITLE
How to change a new data set, not a foggy data set. I don't know how to change the format。Please!

### ISSUE THREAD

**Issue by Cjh2312** [BookerDeWitt/MSBDN-DFF#18]
Hello, I want to change a data set for training, but I found that the data set format used in this paper is. H5, I don't have data set in this format. I only have data set in. JPG format. How can I modify the training code so as to use my own data set? Or do you have any specific methods to change my data set format to. H5 format? This data set in. H5 format is very special, and there must be a lot of conversion details when you synthesize it. Please let me know Thank you very much

**Comment by Cjh2312** [comment]
help me !  i  really need your help ! help !!

**Comment by Cjh2312** [comment]
please! please!

**Comment by BookerDeWitt** [comment]
The code for generating the h5 file is in MSBDN-DFF/HDF5/dehaze_RESIDE_HDF5.m.

**Comment by Cjh2312** [comment]
Thanks,i will try to change a new datasets



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月9日(星期五) 下午2:28
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [BookerDeWitt/MSBDN-DFF] How to change a new data set, not a foggy data set. I don&#39;t know how to change the format。Please! (#18)





 
生成 h5 文件的代码位于 MSBDN-DFF/HDF5/dehaze_RESIDE_HDF5.m中。
 
—
您收到此信息是因为你编写了该线程。
直接回复此电子邮件，在 GitHub 上查看，或取消订阅。
