### ISSUE TITLE
Hello, can you copy a copy of the code you generated for the. H5 dataset？

### ISSUE THREAD

**Issue by sym1998** [BookerDeWitt/MSBDN-DFF#19]
Please！

**Comment by BookerDeWitt** [comment]
We generate the h5 files with matlab. You can find the script in 'MSBDN-DFF/HDF5/dehaze_RESIDE_HDF5.m'

**Comment by sym1998** [comment]
Thanks！

**Comment by sym1998** [comment]
![image](https://user-images.githubusercontent.com/73090077/114166558-755ef680-9960-11eb-9a77-41cdfb187b5d.png)
这个错误是为什么啊

**Comment by sym1998** [comment]
![image](https://user-images.githubusercontent.com/73090077/114166848-d1c21600-9960-11eb-962e-ecec895bc8d6.png)
Why is this mistake？
Please

**Comment by Thekingmoon** [comment]
请问索引超出矩阵维度这个问题解决了吗，谢谢！！
