### ISSUE TITLE
*** ModuleNotFoundError: No module named 'networks.MSBDN-DFF-v1-1'

### ISSUE THREAD

**Issue by yzfly** [BookerDeWitt/MSBDN-DFF#9]
How to load model.pkl file? 

python test.py --checkpoint model.pkl     command failed when load model.pkl

model = torch.load(join(opt.checkpoint, test_list[i]), map_location=lambda storage, loc: storage)

**Comment by BookerDeWitt** [comment]
If you download the newly released code, plz rename the networks/MSBDN-DFF.py to networks/MSBDN-DFF-v1-1.py.

**Comment by yzfly** [comment]
That worked, thank you!
